dist: xenial
language: ruby
rvm:
- 2.6.5
before_script:
- echo -e "Host railsexpress.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 ./railsexpress-key
- ssh-add ./railsexpress-key
- cat ./docker-token | docker login -u stkaes --password-stdin
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_5944808d20a9_key -iv $encrypted_5944808d20a9_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
jobs:
  include:
    - script:
        - docker pull ubuntu:bionic
        - make package-bionic publish-bionic
    - script:
        - docker pull ubuntu:xenial
        - make package-xenial publish-xenial
    - script:
        - docker pull ubuntu:bionic
        - make package-bionic-usr-local publish-bionic-usr-local
    - script:
        - docker pull ubuntu:xenial
        - make package-xenial-usr-local publish-xenial-usr-local
