name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [bionic, focal, jammy]
        arch: ["amd64", "arm64"]
        location: ["", "-usr-local"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Pull base image
        run: make pull-${{ matrix.os }} ARCH=${{ matrix.arch }}

      - name: Install gems
        run: bundle install

      - name: Build package
        run: make package-${{ matrix.os }}${{ matrix.location }} ARCH=${{ matrix.arch }}

      - name: Setup SSH credentials
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/railsexpress.key
          chmod 600 ~/.ssh/railsexpress.key
          cat >>~/.ssh/config <<END
          Host railsexpress.de
            HostName railsexpress.de
            User uploader
            IdentityFile ~/.ssh/railsexpress.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.RAILSEXPRESS_SSH_KEY }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Upload the package
        run: make publish-${{ matrix.os }}${{ matrix.location }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
